USE ota;

DROP TABLE IF EXISTS log;

CREATE TABLE log (
   log_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,   
   log_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   
   log_level VARCHAR(10) NOT NULL,
   log_source VARCHAR(50),
   log_message VARCHAR(1000)
);
